"""Языковые метки для построения промптов"""

PROMPT_LABELS = {
    'ru': {
        'query': '=== ЗАПРОС ПОЛЬЗОВАТЕЛЯ ===',
        'natal_chart': '=== НАТАЛЬНАЯ КАРТА ===',
        'planet_data': '=== ДАННЫЕ ПЛАНЕТЫ ===',
        'aspect_data': '=== ДАННЫЕ АСПЕКТА СИНАСТРИИ ===',
        'found_fragments': '=== НАЙДЕННЫЕ ФРАГМЕНТЫ ИЗ КНИГ ===',
        'analysis': '=== АНАЛИЗ ===',

        'planets_in_houses': 'Планеты в домах:',
        'house_cusps': 'Куспиды домов:',
        'planet': 'Планета',
        'planet1': 'Планета 1',
        'planet2': 'Планета 2',
        'sign': 'Знак',
        'degree': 'Градус',
        'house': 'Дом',
        'house_sign': 'Знак на куспиде дома',
        'motion': 'Движение',
        'retrograde': 'Ретроградная (Rx)',
        'direct': 'Директная (D)',
        'planet_aspects': 'Аспекты планеты:',
        'aspect_type': 'Тип аспекта',
        'orb': 'Орбис',
        'fragment': 'Фрагмент',
        'please_analyze': 'Пожалуйста, дайте подробный анализ.',
        'please_analyze_planet': 'Пожалуйста, дайте подробный анализ этой планеты.',
        'please_analyze_synastry_aspect': 'Пожалуйста, дайте подробный анализ этого аспекта синастрии.',
        'natal_chart_label': 'НАТАЛЬНАЯ КАРТА',
        'planets': 'ПЛАНЕТЫ',
        'houses': 'ДОМА',
        'house_num': 'Дом',
        'pars_fortuna': 'Pars Fortuna',

        # Блок данных прогрессий (progressions_analysis, analysis_service.py) —
        # раньше был захардкожен по-русски независимо от language; ключи ниже
        # чинят это для обоих языков (план:
        # app/services/specs/progressions_synastry_pattern_plan.md).
        'progressions_data_header': '=== ДАННЫЕ ВТОРИЧНЫХ ПРОГРЕССИЙ ===',
        'age': 'Возраст',
        'period': 'Период',
        'house_word': 'дом',
        'progressed_lunar_phase_label': 'ПРОГРЕССИВНАЯ ЛУННАЯ ФАЗА',
        'moon_sun_angle_label': 'угол Луна−Солнце',
        'progressed_ascendant_label': 'Прогрессивный Асцендент',
        'progressed_mc_label': 'Прогрессивный MC',
        'progressed_planets_header': '=== ПРОГРЕССИВНЫЕ ПЛАНЕТЫ (знак, градус, натальный дом, изменения) ===',
        # Слой-маркеры для блока данных (не для вывода модели) — ставятся перед
        # каждой строкой планеты, ЗАГЛАВНЫМИ, без склонения по роду планеты
        # (тот же приём, что ПАРТНЕР1:/ПАРТНЕР2: в synastry_service.py).
        'layer_progressed': 'ПРОГРЕССИВНАЯ',
        'layer_natal': 'НАТАЛЬНАЯ',
        'retrograde_inline': ' (ретроградная)',
        'retrograde_short': ' R',
        'changed_sign_marker': 'СМЕНИЛА ЗНАК (в натале была в {sign})',
        'changed_house_marker': 'ПЕРЕШЛА В ДРУГОЙ ДОМ (в натале была в доме {house})',
        'years_to_next_sign_marker': 'сменит знак примерно через {years} лет',
        'natal_chart_overlay_header': '=== НАТАЛЬНАЯ КАРТА (основа для оверлея) ===',
        'natal_planets_list_label': 'Натальные планеты (знак, дом):',
    },

    'en': {
        'query': '=== USER QUERY ===',
        'natal_chart': '=== NATAL CHART ===',
        'planet_data': '=== PLANET DATA ===',
        'aspect_data': '=== SYNASTRY ASPECT DATA ===',
        'found_fragments': '=== FOUND BOOK FRAGMENTS ===',
        'analysis': '=== ANALYSIS ===',

        'planets_in_houses': 'Planets in houses:',
        'house_cusps': 'House cusps:',
        'planet': 'Planet',
        'planet1': 'Planet 1',
        'planet2': 'Planet 2',
        'sign': 'Sign',
        'degree': 'Degree',
        'house': 'House',
        'house_sign': 'House sign',
        'motion': 'Motion',
        'retrograde': 'Retrograde (Rx)',
        'direct': 'Direct (D)',
        'planet_aspects': 'Planet aspects:',
        'aspect_type': 'Aspect type',
        'orb': 'Orb',
        'fragment': 'Fragment',
        'please_analyze': 'Please provide detailed analysis.',
        'please_analyze_planet': 'Please provide detailed analysis of this planet.',
        'please_analyze_synastry_aspect': 'Please provide detailed analysis of this synastry aspect.',
        'natal_chart_label': 'NATAL CHART',
        'planets': 'PLANETS',
        'houses': 'HOUSES',
        'house_num': 'House',
        'pars_fortuna': 'Pars Fortuna',

        'progressions_data_header': '=== SECONDARY PROGRESSIONS DATA ===',
        'age': 'Age',
        'period': 'Period',
        'house_word': 'house',
        'progressed_lunar_phase_label': 'PROGRESSED LUNAR PHASE',
        'moon_sun_angle_label': 'Moon-Sun angle',
        'progressed_ascendant_label': 'Progressed Ascendant',
        'progressed_mc_label': 'Progressed MC',
        'progressed_planets_header': '=== PROGRESSED PLANETS (sign, degree, natal house, changes) ===',
        'layer_progressed': 'PROGRESSED',
        'layer_natal': 'NATAL',
        'retrograde_inline': ' (retrograde)',
        'retrograde_short': ' R',
        'changed_sign_marker': 'CHANGED SIGN (was in {sign} in the natal chart)',
        'changed_house_marker': 'MOVED TO A DIFFERENT HOUSE (was in house {house} in the natal chart)',
        'years_to_next_sign_marker': 'will change sign in about {years} years',
        'natal_chart_overlay_header': '=== NATAL CHART (basis for the overlay) ===',
        'natal_planets_list_label': 'Natal planets (sign, house):',
    },
}


def get_labels(language: str):
    """Получить метки для нужного языка с fallback на английский"""
    return PROMPT_LABELS.get(language, PROMPT_LABELS['en'])
