"""Языковые метки для построения промптов"""

PROMPT_LABELS = {
    'ru': {
        'query': '=== ЗАПРОС ПОЛЬЗОВАТЕЛЯ ===',
        'natal_chart': '=== НАТАЛЬНАЯ КАРТА ===',
        'planet_data': '=== ДАННЫЕ ПЛАНЕТЫ ===',
        'aspect_data': '=== ДАННЫЕ АСПЕКТА СИНАСТРИИ ===',
        'found_fragments': '=== НАЙДЕННЫЕ ФРАГМЕНТЫ ИЗ КНИГ ===',
        'analysis': '=== АНАЛИЗ ===',

        'planets_in_houses': 'Планеты в домах:',
        'house_cusps': 'Куспиды домов:',
        'planet': 'Планета',
        'planet1': 'Планета 1',
        'planet2': 'Планета 2',
        'sign': 'Знак',
        'degree': 'Градус',
        'house': 'Дом',
        'house_sign': 'Знак на куспиде дома',
        'motion': 'Движение',
        'retrograde': 'Ретроградная (Rx)',
        'direct': 'Директная (D)',
        'planet_aspects': 'Аспекты планеты:',
        'aspect_type': 'Тип аспекта',
        'orb': 'Орбис',
        'fragment': 'Фрагмент',
        'please_analyze': 'Пожалуйста, дайте подробный анализ.',
        'please_analyze_planet': 'Пожалуйста, дайте подробный анализ этой планеты.',
        'please_analyze_synastry_aspect': 'Пожалуйста, дайте подробный анализ этого аспекта синастрии.',
        'natal_chart_label': 'НАТАЛЬНАЯ КАРТА',
        'planets': 'ПЛАНЕТЫ',
        'houses': 'ДОМА',
        'house_num': 'Дом',
        'pars_fortuna': 'Pars Fortuna',
    },
    
    'en': {
        'query': '=== USER QUERY ===',
        'natal_chart': '=== NATAL CHART ===',
        'planet_data': '=== PLANET DATA ===',
        'aspect_data': '=== SYNASTRY ASPECT DATA ===',
        'found_fragments': '=== FOUND BOOK FRAGMENTS ===',
        'analysis': '=== ANALYSIS ===',

        'planets_in_houses': 'Planets in houses:',
        'house_cusps': 'House cusps:',
        'planet': 'Planet',
        'planet1': 'Planet 1',
        'planet2': 'Planet 2',
        'sign': 'Sign',
        'degree': 'Degree',
        'house': 'House',
        'house_sign': 'House sign',
        'motion': 'Motion',
        'retrograde': 'Retrograde (Rx)',
        'direct': 'Direct (D)',
        'planet_aspects': 'Planet aspects:',
        'aspect_type': 'Aspect type',
        'orb': 'Orb',
        'fragment': 'Fragment',
        'please_analyze': 'Please provide detailed analysis.',
        'please_analyze_planet': 'Please provide detailed analysis of this planet.',
        'please_analyze_synastry_aspect': 'Please provide detailed analysis of this synastry aspect.',
        'natal_chart_label': 'NATAL CHART',
        'planets': 'PLANETS',
        'houses': 'HOUSES',
        'house_num': 'House',
        'pars_fortuna': 'Pars Fortuna',
    },
}


def get_labels(language: str):
    """Получить метки для нужного языка с fallback на английский"""
    return PROMPT_LABELS.get(language, PROMPT_LABELS['en'])
