"""Language labels used to build prompts"""

PROMPT_LABELS = {
    'ru': {
        'query': '=== ЗАПРОС ПОЛЬЗОВАТЕЛЯ ===',
        'natal_chart': '=== НАТАЛЬНАЯ КАРТА ===',
        'planet_data': '=== ДАННЫЕ ПЛАНЕТЫ ===',
        'aspect_data': '=== ДАННЫЕ АСПЕКТА СИНАСТРИИ ===',
        'found_fragments': '=== НАЙДЕННЫЕ ФРАГМЕНТЫ ИЗ КНИГ ===',
        'analysis': '=== АНАЛИЗ ===',

        'planets_in_houses': 'Планеты в домах:',
        'house_cusps': 'Куспиды домов:',
        'planet': 'Планета',
        'planet1': 'Планета 1',
        'planet2': 'Планета 2',
        'sign': 'Знак',
        'degree': 'Градус',
        'house': 'Дом',
        'house_sign': 'Знак на куспиде дома',
        'motion': 'Движение',
        'retrograde': 'Ретроградная (Rx)',
        'direct': 'Директная (D)',
        'planet_aspects': 'Аспекты планеты:',
        'aspect_type': 'Тип аспекта',
        'orb': 'Орбис',
        'fragment': 'Фрагмент',
        'please_analyze': 'Пожалуйста, дайте подробный анализ.',
        'please_analyze_planet': 'Пожалуйста, дайте подробный анализ этой планеты.',
        'please_analyze_synastry_aspect': 'Пожалуйста, дайте подробный анализ этого аспекта синастрии.',
        'natal_chart_label': 'НАТАЛЬНАЯ КАРТА',
        'planets': 'ПЛАНЕТЫ',
        'houses': 'ДОМА',
        'house_num': 'Дом',
        'pars_fortuna': 'Pars Fortuna',

        # Progressions data block (progressions_analysis, analysis_service.py) —
        # used to be hardcoded in Russian regardless of language; the keys below
        # fix this for both languages (plan:
        # app/services/specs/progressions_synastry_pattern_plan.md).
        'progressions_data_header': '=== ДАННЫЕ ВТОРИЧНЫХ ПРОГРЕССИЙ ===',
        'age': 'Возраст',
        'period': 'Период',
        'house_word': 'дом',
        'progressed_lunar_phase_label': 'ПРОГРЕССИВНАЯ ЛУННАЯ ФАЗА',
        'moon_sun_angle_label': 'угол Луна−Солнце',
        'progressed_ascendant_label': 'Прогрессивный Асцендент',
        'progressed_mc_label': 'Прогрессивный MC',
        'progressed_planets_header': '=== ПРОГРЕССИВНЫЕ ПЛАНЕТЫ (знак, градус, натальный дом, изменения) ===',
        # Layer markers for the data block (not for the model's output) — placed
        # before each planet line, UPPERCASE, without gender-declining the planet
        # (same trick as ПАРТНЕР1:/ПАРТНЕР2: in synastry_service.py).
        'layer_progressed': 'ПРОГРЕССИВНАЯ',
        'layer_natal': 'НАТАЛЬНАЯ',
        'retrograde_inline': ' (ретроградная)',
        'retrograde_short': ' R',
        'changed_sign_marker': 'СМЕНИЛА ЗНАК (в натале была в {sign})',
        'changed_house_marker': 'ПЕРЕШЛА В ДРУГОЙ ДОМ (в натале была в доме {house})',
        'years_to_next_sign_marker': 'сменит знак примерно через {years} лет',
        'natal_chart_overlay_header': '=== НАТАЛЬНАЯ КАРТА (основа для оверлея) ===',
        'natal_planets_list_label': 'Натальные планеты (знак, дом):',

        # Transits data block (transits_analysis, analysis_service.py) — same
        # reason and same plan as progressions: used to be hardcoded in
        # Russian regardless of language.
        'transits_data_header': '=== ДАННЫЕ ТРАНЗИТОВ ===',
        'day_label': 'День',
        'transit_place_label': 'Место транзита',
        'not_specified': 'не указано',
        'coordinates_label': 'координаты',
        'transiting_ascendant_label': 'Транзитный Асцендент',
        'transiting_mc_label': 'Транзитный MC',
        'day_lunar_phase_label': 'ЛУННАЯ ФАЗА ДНЯ',
        'transit_planets_header': '=== ТРАНЗИТНЫЕ ПЛАНЕТЫ (знак, градус, дома) ===',
        # Layer marker for the transits data block — same trick as
        # layer_progressed/layer_natal.
        'layer_transit': 'ТРАНЗИТНАЯ',
        'natal_house_word': 'натальный дом',
        'transit_house_word': 'транзитный дом',
        'slow_planet_marker': ' [медленная — фоновая тема]',
    },

    'en': {
        'query': '=== USER QUERY ===',
        'natal_chart': '=== NATAL CHART ===',
        'planet_data': '=== PLANET DATA ===',
        'aspect_data': '=== SYNASTRY ASPECT DATA ===',
        'found_fragments': '=== FOUND BOOK FRAGMENTS ===',
        'analysis': '=== ANALYSIS ===',

        'planets_in_houses': 'Planets in houses:',
        'house_cusps': 'House cusps:',
        'planet': 'Planet',
        'planet1': 'Planet 1',
        'planet2': 'Planet 2',
        'sign': 'Sign',
        'degree': 'Degree',
        'house': 'House',
        'house_sign': 'House sign',
        'motion': 'Motion',
        'retrograde': 'Retrograde (Rx)',
        'direct': 'Direct (D)',
        'planet_aspects': 'Planet aspects:',
        'aspect_type': 'Aspect type',
        'orb': 'Orb',
        'fragment': 'Fragment',
        'please_analyze': 'Please provide detailed analysis.',
        'please_analyze_planet': 'Please provide detailed analysis of this planet.',
        'please_analyze_synastry_aspect': 'Please provide detailed analysis of this synastry aspect.',
        'natal_chart_label': 'NATAL CHART',
        'planets': 'PLANETS',
        'houses': 'HOUSES',
        'house_num': 'House',
        'pars_fortuna': 'Pars Fortuna',

        'progressions_data_header': '=== SECONDARY PROGRESSIONS DATA ===',
        'age': 'Age',
        'period': 'Period',
        'house_word': 'house',
        'progressed_lunar_phase_label': 'PROGRESSED LUNAR PHASE',
        'moon_sun_angle_label': 'Moon-Sun angle',
        'progressed_ascendant_label': 'Progressed Ascendant',
        'progressed_mc_label': 'Progressed MC',
        'progressed_planets_header': '=== PROGRESSED PLANETS (sign, degree, natal house, changes) ===',
        'layer_progressed': 'PROGRESSED',
        'layer_natal': 'NATAL',
        'retrograde_inline': ' (retrograde)',
        'retrograde_short': ' R',
        'changed_sign_marker': 'CHANGED SIGN (was in {sign} in the natal chart)',
        'changed_house_marker': 'MOVED TO A DIFFERENT HOUSE (was in house {house} in the natal chart)',
        'years_to_next_sign_marker': 'will change sign in about {years} years',
        'natal_chart_overlay_header': '=== NATAL CHART (basis for the overlay) ===',
        'natal_planets_list_label': 'Natal planets (sign, house):',

        'transits_data_header': '=== TRANSITS DATA ===',
        'day_label': 'Day',
        'transit_place_label': 'Transit location',
        'not_specified': 'not specified',
        'coordinates_label': 'coordinates',
        'transiting_ascendant_label': 'Transiting Ascendant',
        'transiting_mc_label': 'Transiting MC',
        'day_lunar_phase_label': "TODAY'S LUNAR PHASE",
        'transit_planets_header': '=== TRANSITING PLANETS (sign, degree, houses) ===',
        'layer_transit': 'TRANSITING',
        'natal_house_word': 'natal house',
        'transit_house_word': 'transit house',
        'slow_planet_marker': ' [slow — background theme]',
    },

    'uk': {
        'query': '=== ЗАПИТ КОРИСТУВАЧА ===',
        'natal_chart': '=== НАТАЛЬНА КАРТА ===',
        'planet_data': '=== ДАНІ ПЛАНЕТИ ===',
        'aspect_data': '=== ДАНІ АСПЕКТУ СИНАСТРІЇ ===',
        'found_fragments': '=== ЗНАЙДЕНІ ФРАГМЕНТИ З КНИГ ===',
        'analysis': '=== АНАЛІЗ ===',

        'planets_in_houses': 'Планети в будинках:',
        'house_cusps': 'Куспіди будинків:',
        'planet': 'Планета',
        'planet1': 'Планета 1',
        'planet2': 'Планета 2',
        'sign': 'Знак',
        'degree': 'Градус',
        'house': 'Будинок',
        'house_sign': 'Знак на куспіді будинку',
        'motion': 'Рух',
        'retrograde': 'Ретроградна (Rx)',
        'direct': 'Директна (D)',
        'planet_aspects': 'Аспекти планети:',
        'aspect_type': 'Тип аспекту',
        'orb': 'Орбіс',
        'fragment': 'Фрагмент',
        'please_analyze': 'Будь ласка, дай детальний аналіз.',
        'please_analyze_planet': 'Будь ласка, дай детальний аналіз цієї планети.',
        'please_analyze_synastry_aspect': 'Будь ласка, дай детальний аналіз цього аспекту синастрії.',
        'natal_chart_label': 'НАТАЛЬНА КАРТА',
        'planets': 'ПЛАНЕТИ',
        'houses': 'БУДИНКИ',
        'house_num': 'Будинок',
        'pars_fortuna': 'Pars Fortuna',

        'progressions_data_header': '=== ДАНІ ВТОРИННИХ ПРОГРЕСІЙ ===',
        'age': 'Вік',
        'period': 'Період',
        'house_word': 'будинок',
        'progressed_lunar_phase_label': 'ПРОГРЕСИВНА МІСЯЧНА ФАЗА',
        'moon_sun_angle_label': 'кут Місяць−Сонце',
        'progressed_ascendant_label': 'Прогресивний Асцендент',
        'progressed_mc_label': 'Прогресивний MC',
        'progressed_planets_header': '=== ПРОГРЕСИВНІ ПЛАНЕТИ (знак, градус, натальний будинок, зміни) ===',
        'layer_progressed': 'ПРОГРЕСИВНА',
        'layer_natal': 'НАТАЛЬНА',
        'retrograde_inline': ' (ретроградна)',
        'retrograde_short': ' R',
        'changed_sign_marker': 'ЗМІНИЛА ЗНАК (у наталі була в {sign})',
        'changed_house_marker': 'ПЕРЕЙШЛА В ІНШИЙ БУДИНОК (у наталі була в будинку {house})',
        'years_to_next_sign_marker': 'змінить знак приблизно через {years} років',
        'natal_chart_overlay_header': '=== НАТАЛЬНА КАРТА (основа для оверлею) ===',
        'natal_planets_list_label': 'Натальні планети (знак, будинок):',

        'transits_data_header': '=== ДАНІ ТРАНЗИТІВ ===',
        'day_label': 'День',
        'transit_place_label': 'Місце транзиту',
        'not_specified': 'не вказано',
        'coordinates_label': 'координати',
        'transiting_ascendant_label': 'Транзитний Асцендент',
        'transiting_mc_label': 'Транзитний MC',
        'day_lunar_phase_label': 'МІСЯЧНА ФАЗА ДНЯ',
        'transit_planets_header': '=== ТРАНЗИТНІ ПЛАНЕТИ (знак, градус, будинки) ===',
        'layer_transit': 'ТРАНЗИТНА',
        'natal_house_word': 'натальний будинок',
        'transit_house_word': 'транзитний будинок',
        'slow_planet_marker': ' [повільна — фонова тема]',
    },
}


def get_labels(language: str):
    """Get the labels for the given language, falling back to English"""
    return PROMPT_LABELS.get(language, PROMPT_LABELS['en'])
